name: Ubuntu 22.04 CI (GCC 11)

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - {cfg: Release}
          - {cfg: Debug}
    steps:
      - uses: actions/checkout@v4
      - name: Use cmake
        run: |
          mkdir build &&
          cd build &&
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.cfg}} &&
          cmake --build .   &&
          ctest --output-on-failure
